// Chat completions. The browser cannot call most providers' /chat/completions
// directly (no CORS headers on their side), so this route forwards the request
// and streams the SSE body straight back.
//
// IT NOW FORWARDS TO THE BACKEND, NOT TO THE PROVIDER.
//
// This is the one route where the move was NOT forced by a geo-block. The LLM
// providers serve Vercel's regions perfectly well — arguably better than a
// backend in APAC does. It moved because the rule is that no Next.js route calls
// a third party, and an exception here would be the one place a future reader
// has to remember is different.
//
// THE COST, STATED PLAINLY: the response crosses one extra hop before the first
// token lands (provider -> backend -> here -> browser), so time-to-first-token is
// higher than it was. Streaming is preserved at every hop, so this is latency and
// not a behaviour change — the answer still arrives token by token rather than as
// one block at the end. To revert, have `callBackend` POST to `upstreamUrl` with
// the provider's key instead of to the backend; nothing else here changes.
//
// Nothing is logged or persisted. The API key passes through in memory for the
// duration of one request, exactly as before — it now transits one more machine,
// which is the operator's own.

import {
  buildChatCompletionsUrl,
  looksLikeMissingV1,
  parseUpstreamErrorMessage,
  withV1Inserted,
} from '@/lib/chatUpstream';
import { backendOrigin } from '@/lib/api/backendProxy.server';

// NODE RUNTIME. THIS USED TO BE `edge` AND THAT IS WHAT BROKE "Ask Agent".
//
// The symptom was a 403 the operator saw in the chat panel and nowhere else:
//
//     Upstream error 403: Direct IP access is not allowed in Vercel's Edge
//     environment (hostname: 68.233.106.208)
//
// That message is generated by VERCEL, not by the backend and not by the model
// provider. Vercel's Edge runtime refuses `fetch()` to a bare IP literal; it will
// only dial a DNS hostname. The backend is reached at `BACKEND_INTERNAL_URL`,
// which on this deployment is `http://<ip>:8000`, so the hop out of this route
// was rejected before a packet left Vercel.
//
// WHY ONLY THIS ROUTE. Every other route that talks to the backend goes through
// `proxyToBackend`/`app/api/backend/[...path]` on the Node runtime, where a raw
// IP is fine. This was the ONLY edge route in the app (`grep "runtime = 'edge'"`
// returns one hit), which is exactly why "Ask Agent" was the only broken page
// while market data, positions and the pipeline all kept working. A whole-app
// outage would have been found in minutes; one page failing looked like a chat
// bug and sent three sessions looking at the LLM config.
//
// THE ORIGINAL REASON FOR EDGE NO LONGER HOLDS. It said Vercel's Node functions
// buffer the full response before returning it. That was true of the older
// Serverless Function model; App Router route handlers on the Node runtime
// stream a `ReadableStream` body through Vercel today, which is why the SSE
// passthrough below is unchanged and still arrives token by token.
//
// DO NOT PUT THIS BACK ON EDGE to shave latency. `tests/chatRuntime.test.ts`
// fails if this line changes, because the failure it causes is invisible in
// local dev — localhost is a hostname, so edge dials it happily and the bug only
// appears once deployed against an IP-addressed backend.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type ChatBody = {
  apiKey: string;
  baseUrl?: string;
  model?: string;
  messages: { role: string; content: string }[];
  temperature?: number;
  maxTokens?: number;
};

export async function POST(req: Request) {
  let body: ChatBody;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { apiKey, baseUrl, model, messages, temperature, maxTokens } = body;

  // Validated here, before the hop. A missing key is the caller's mistake and
  // should not cost a round trip to be told so.
  if (!apiKey) {
    return Response.json({ error: 'Missing API key' }, { status: 400 });
  }
  if (!Array.isArray(messages) || messages.length === 0) {
    return Response.json({ error: 'Missing messages' }, { status: 400 });
  }

  // Self-hosted OpenAI-compatible servers (Ollama, LM Studio, vLLM, LiteLLM) are
  // very commonly pointed at without the trailing /v1. The correction is applied
  // HERE rather than in the backend because `lib/chatUpstream.ts` already owns
  // that logic and has tests against the exact 404 signature — duplicating it in
  // Python would create a second, drifting copy of a fiddly heuristic.
  const resolvedBaseUrl = baseUrl || 'https://integrate.api.nvidia.com/v1';
  const upstreamUrl = buildChatCompletionsUrl(resolvedBaseUrl);

  const backendUrl = `${backendOrigin()}/api/ai/chat`;

  async function callBackend(providerBaseUrl: string): Promise<Response> {
    return fetch(backendUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(process.env.TRADES_API_KEY ? { Authorization: `Bearer ${process.env.TRADES_API_KEY}` } : {}),
      },
      body: JSON.stringify({
        apiKey,
        baseUrl: providerBaseUrl,
        model,
        messages,
        temperature,
        maxTokens,
      }),
    });
  }

  let upstreamRes: Response;
  try {
    upstreamRes = await callBackend(resolvedBaseUrl);
  } catch (err) {
    const message = err instanceof Error ? err.message : 'unknown error';
    // Names WHICH hop failed. "The backend is unreachable" and "the model
    // provider rejected the key" are both a 502 to the browser and have
    // completely different fixes.
    return Response.json(
      {
        error:
          `Could not reach the trading backend at ${backendOrigin()} (${message}). This is the ` +
          `Vercel-to-backend hop, not the model provider — check the backend is running and its ` +
          `port is open.`,
      },
      { status: 502 },
    );
  }

  // THE MISSING-/v1 RETRY, PRESERVED ACROSS THE MOVE.
  //
  // Self-hosted OpenAI-compatible servers are very commonly pointed at without
  // the trailing /v1, and Go's default handler answers "404 page not found".
  // Rather than fail on that one-character mistake, the specific signature is
  // detected and retried once against the corrected URL.
  //
  // This only works because the backend propagates the PROVIDER's status code
  // instead of wrapping the error in a 200 SSE frame — see its docstring. If it
  // ever starts returning 200-with-an-error, this retry silently stops
  // happening and the misconfiguration becomes opaque again.
  let retriedUrl: string | undefined;
  if (!upstreamRes.ok) {
    const text = await upstreamRes.clone().text().catch(() => '');
    if (looksLikeMissingV1(upstreamRes.status, text, upstreamUrl)) {
      const fixedBase = withV1Inserted(resolvedBaseUrl);
      if (fixedBase) {
        retriedUrl = buildChatCompletionsUrl(fixedBase);
        try {
          upstreamRes = await callBackend(fixedBase);
        } catch {
          // The retry could not even connect — fall through and report the
          // original error rather than the retry's.
        }
      }
    }
  }

  if (!upstreamRes.ok || !upstreamRes.body) {
    const text = await upstreamRes.text().catch(() => '');
    return Response.json(
      { error: parseUpstreamErrorMessage(upstreamRes.status, text, upstreamUrl, retriedUrl) },
      { status: upstreamRes.status || 502 },
    );
  }

  // The body is piped through untouched. Reading it here — even to inspect it —
  // would buffer the whole answer and turn a token-by-token stream into one
  // long pause followed by a wall of text.
  return new Response(upstreamRes.body, {
    status: 200,
    headers: {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no', // tells nginx-style proxies not to buffer this response
    },
  });
}
