"""Regenerate the endpoint tables in docs/API_REFERENCE.md from the live app.

WHY THIS IS GENERATED RATHER THAN HAND-WRITTEN
----------------------------------------------
A hand-maintained API table drifts the first time someone adds a route and
forgets the doc, and a route table that is wrong is worse than none — it sends
people to test endpoints that do not exist and hides ones that do.

More importantly, the **Auth** column is read from each route's actual
dependencies, not from a note someone wrote. If a route silently loses its
`require_write_auth` dependency, this table changes, and on
`/api/operator/exchange/*` that is the difference between "authenticated" and
"anyone who can reach the port can place a real order".

Usage:
    .venv/Scripts/python.exe scripts/generate_api_reference.py

It rewrites only the block between the two marker comments in the doc, so the
prose around it is preserved.
"""

from __future__ import annotations

import pathlib
import sys
from collections import defaultdict

# Import the app the same way uvicorn does, from the repo root.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from backend.core.auth import require_write_auth  # noqa: E402
from backend.main import app  # noqa: E402

START = "<!-- BEGIN GENERATED ENDPOINTS -->"
END = "<!-- END GENERATED ENDPOINTS -->"

# Group prefix -> heading. Order here is the order in the doc: the things an
# operator reaches for first come first, not alphabetical.
GROUPS = [
    ("/api/monitoring", "Health & status"),
    ("/api/marketdata", "Market data — third-party upstreams"),
    ("/api/market", "Market data — the agent's ccxt view"),
    ("/api/exchange", "Exchange status (READ-ONLY)"),
    ("/api/operator", "Operator exchange — PLACES REAL ORDERS"),
    ("/api/admin", "Kill switch & trading mode"),
    ("/api/dashboard", "Dashboard & event stream"),
    ("/api/graphs", "LangGraph reasoning layer"),
    ("/api/execution", "Execution log & audit"),
    ("/api/catalog", "Catalog — orders, strategies, replay"),
    ("/api/memory", "Memory system"),
    ("/api/research", "Research & hypotheses"),
    ("/api/knowledge", "Knowledge graph"),
    ("/api/missions", "Missions"),
    ("/api/agents", "Agent tasks"),
    ("/api/ai", "AI routing & chat proxy"),
    ("/api/polymarket", "Polymarket feed"),
]


def collect():
    """Routes, their auth requirement, and the WebSocket paths.

    FastAPI defers `include_router`, so `app.routes` holds wrapper objects rather
    than the real routes — the routes live on `original_router` with UNPREFIXED
    paths, and the prefix is on `include_context`. WebSockets are absent from the
    OpenAPI schema entirely, which is why they are gathered separately here.
    """
    auth_paths = set()
    ws_paths = []

    for entry in app.routes:
        router = getattr(entry, "original_router", None)
        prefix = getattr(getattr(entry, "include_context", None), "prefix", "") or ""
        for route in getattr(router, "routes", []) if router else []:
            full = f"{prefix}{route.path}"
            if "WebSocket" in type(route).__name__:
                ws_paths.append(full)
                continue
            deps = [getattr(d, "dependency", None) for d in getattr(route, "dependencies", [])]
            if require_write_auth in deps:
                auth_paths.add(full)

    spec = app.openapi()
    rows = []
    for path, operations in spec["paths"].items():
        for method, op in operations.items():
            if method not in ("get", "post", "put", "delete", "patch"):
                continue
            names = [p["name"] for p in op.get("parameters", [])]
            rows.append({
                "path": path,
                "method": method.upper(),
                "params": [n for n in names if n != "authorization"],
                "body": bool(op.get("requestBody")),
                # Two ways a route declares auth in this codebase: a router-level
                # dependency, or an explicit `authorization` header parameter.
                "auth": path in auth_paths or "authorization" in names,
            })
    return rows, sorted(ws_paths), len(spec["paths"])


def group_of(path: str) -> str:
    for prefix, _ in sorted(GROUPS, key=lambda g: -len(g[0])):
        if path.startswith(prefix):
            return prefix
    return "other"


def render(rows, ws_paths, path_count) -> str:
    grouped = defaultdict(list)
    for row in rows:
        grouped[group_of(row["path"])].append(row)

    lines = [
        START,
        "",
        f"*{len(rows)} operations across {path_count} paths, "
        f"{sum(1 for r in rows if r['auth'])} requiring auth, plus {len(ws_paths)} WebSockets. "
        f"Generated by `scripts/generate_api_reference.py`.*",
        "",
    ]

    for prefix, title in GROUPS:
        items = sorted(grouped.get(prefix, []), key=lambda r: (r["path"], r["method"]))
        if not items:
            continue
        lines += [f"### {title}", "", "| Method | Path | Query / body | Auth |", "|---|---|---|---|"]
        for row in items:
            bits = []
            if row["params"]:
                bits.append("`" + "`, `".join(row["params"]) + "`")
            if row["body"]:
                bits.append("JSON body")
            lines.append(
                f"| {row['method']} | `{row['path']}` | {' + '.join(bits) or '-'} | "
                f"{'**yes**' if row['auth'] else 'no'} |"
            )
        lines.append("")

    leftover = sorted(grouped.get("other", []), key=lambda r: r["path"])
    if leftover:
        # Surfaced rather than dropped: an ungrouped route means GROUPS is out of
        # date, and silently omitting it is how a route becomes undocumented.
        lines += ["### Ungrouped (add a prefix to GROUPS in the generator)", "",
                  "| Method | Path |", "|---|---|"]
        lines += [f"| {r['method']} | `{r['path']}` |" for r in leftover]
        lines.append("")

    lines += ["### WebSockets", "", "| Path |", "|---|"]
    lines += [f"| `{p}` |" for p in ws_paths]
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    doc = pathlib.Path(__file__).resolve().parents[1] / "docs" / "API_REFERENCE.md"
    if not doc.exists():
        print(f"error: {doc} does not exist", file=sys.stderr)
        return 1

    text = doc.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: markers {START} / {END} not found in {doc}", file=sys.stderr)
        return 1

    rows, ws_paths, path_count = collect()
    before = text.split(START)[0]
    after = text.split(END)[1]
    doc.write_text(before + render(rows, ws_paths, path_count) + after, encoding="utf-8")

    print(f"Updated {doc.name}: {len(rows)} operations, {len(ws_paths)} websockets.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
